export enum EmailType {
    ACCOUNT_INVITATION = 1,
    JOB_APPLY_INVITATION = 2,
    PROFILE_SHARING = 3,
    ACCOUNT_SIGNUP_SUCCESSFUL = 4,
    ASSESSMENTS_COMPLETED = 5,
    APPLICATION_REJECTED = 6,
    APPLICATION_REMINDER = 7,
    APPLICATION_RECEIVED = 8,
    ASSESSMENT_REMINDER = 9,
    APPLICATION_SHORTLISTED = 10,
    VIDEO_INTERVIEW = 11,
    ASSESSMENT_INVITATION = 17,
}
